# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cut.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cut.proto',
  package='cut',
  syntax='proto2',
  serialized_pb=_b('\n\tcut.proto\x12\x03\x63ut\"\xa4\x01\n\x07Segment\x12\x0f\n\x07out_buf\x18\x01 \x01(\x0c\x12\x14\n\x0c\x63ompound_buf\x18\x02 \x01(\x0c\x12\x12\n\nfinger_num\x18\x03 \x01(\r\x12\x16\n\nfinger_arr\x18\x04 \x03(\x04\x42\x02\x10\x01\x12\x16\n\nweight_arr\x18\x05 \x03(\rB\x02\x10\x01\x12\x14\n\x08type_arr\x18\x06 \x03(\rB\x02\x10\x01\x12\x18\n\x0cposition_arr\x18\x07 \x03(\rB\x02\x10\x01')
)




_SEGMENT = _descriptor.Descriptor(
  name='Segment',
  full_name='cut.Segment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='out_buf', full_name='cut.Segment.out_buf', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='compound_buf', full_name='cut.Segment.compound_buf', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='finger_num', full_name='cut.Segment.finger_num', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='finger_arr', full_name='cut.Segment.finger_arr', index=3,
      number=4, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
    _descriptor.FieldDescriptor(
      name='weight_arr', full_name='cut.Segment.weight_arr', index=4,
      number=5, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
    _descriptor.FieldDescriptor(
      name='type_arr', full_name='cut.Segment.type_arr', index=5,
      number=6, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
    _descriptor.FieldDescriptor(
      name='position_arr', full_name='cut.Segment.position_arr', index=6,
      number=7, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=183,
)

DESCRIPTOR.message_types_by_name['Segment'] = _SEGMENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Segment = _reflection.GeneratedProtocolMessageType('Segment', (_message.Message,), dict(
  DESCRIPTOR = _SEGMENT,
  __module__ = 'cut_pb2'
  # @@protoc_insertion_point(class_scope:cut.Segment)
  ))
_sym_db.RegisterMessage(Segment)


_SEGMENT.fields_by_name['finger_arr'].has_options = True
_SEGMENT.fields_by_name['finger_arr']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
_SEGMENT.fields_by_name['weight_arr'].has_options = True
_SEGMENT.fields_by_name['weight_arr']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
_SEGMENT.fields_by_name['type_arr'].has_options = True
_SEGMENT.fields_by_name['type_arr']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
_SEGMENT.fields_by_name['position_arr'].has_options = True
_SEGMENT.fields_by_name['position_arr']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
# @@protoc_insertion_point(module_scope)
